standard random function is added
dojoengine/origami pull request #32
Opened 2023-12-27 19:22 UTC by demirbey05

Closes #

## Introduced changes

-

## Checklist

- [ ] Linked relevant issue
- [ ] Updated relevant documentation
- [ ] Added relevant tests
- [ ] Add a dedicated CI job for new examples
- [ ] Performed self-review of the code

2023-12-28 09:30 UTC, ponderingdemocritus commented
Thanks for the PR! 

- Can you please fix the Cairo formatting -> https://docs.swmansion.com/scarb/docs/guides/formatting.html
- Can you add comments

2023-12-29 20:13 UTC, demirbey05 commented
Hello @ponderingdemocritus  I added comments and fixed the format. Thanks for your assistance. I will be waiting for your feedback.

2024-01-03 17:44 UTC, Bal7hazar requested changes
Thanks for your contribution and sorry for the late review.

I think this feature is interesting to have in this high level format.

Some minor changes to implement.

2024-01-03 17:44 UTC, Bal7hazar commented on crates/src/random/random.cairo
> +        let range: u256 = (max_number - min_number).into();
I think it should be `max - min + 1`, otherwise you exclude the upper bound

2024-01-03 17:44 UTC, Bal7hazar commented on crates/src/random/random.cairo
> +        assert(min_number <= max_number, 'wrong interval');
`min_number < max_number` because N % 0 is not defined

2024-01-03 17:44 UTC, Bal7hazar commented on crates/src/random/random.cairo
> +    fn getRandomWithInterval(ref self: Random, min_number: u256, max_number: u256) -> u256;
`getRandomWithInterval` should be in snake case.

Also `random.get_random...` is a bit ... you know, what about `random.get_within_interval`

2024-03-08 01:49 UTC, ponderingdemocritus commented
@demirbey05 will you be finishing this?

2024-04-07 08:25 UTC, closed without merging